twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'bootstrap_5_layout.html.twig' ]
  globals:
    WhatTodoNow: '@app.what_todo_now'
when@test:
  twig:
    strict_variables: true
